Fixes deprecations and failing specs
Why:

* _DEPRECATION WARNING: The configuration option
`config.serve_static_assets` has been renamed to
`config.serve_static_files` to clarify its role._
* _DEPRECATION WARNING: Currently, Active Record suppresses errors
raised within `after_rollback`/`after_commit` callbacks and only print
them to the logs. In the next version, these errors will no longer be
suppressed._
* _[DEPRECATION] Clearance's `authorize` before_filter is deprecated.
Use `require_login` instead._
* Some specs were failing with the following error:
_ActionController::RoutingError: The controller-level `respond_to`
feature has been extracted to the `responders` gem_.
* _NoMethodError at /books/1/edit: undefined method `persisted?` for
* `spec/features/books/edit_book.feature` was failing

This change addresses the need by:

* Refactoring `config.serve_static_assets` to
`config.serve_static_files` in production and test configurations.
* Adding `config.active_record.raise_in_transactional_callbacks =
true` the application base configuration to suppress the deprecation
warning.
* Refactoring `before_action` callbacks to use Clearance's new
`require_login`.
* Adding the `responders` gem.
* Fixing books decorator to expose required method for edit form.
* Fixing update on `BooksController` to use the private method for
retrieving the model instead of using a non assigned variable.
* Fixing CI badge in the README (wrong CI service & project).